### ISSUE TITLE
Hello, I'm playing "warmane" World of Warcraft. I am accessing a server in Germany from China. Is it suitable?

### ISSUE THREAD

**Issue by hkbbdx** [xiahualiu/wg_gaming_installer#1]
Hello, I'm playing "warmane" World of Warcraft. I am accessing a server in Germany from China. Is it suitable?

**Comment by xiahualiu** [comment]
Yes, you just need to find a good server to overcome the GFW. Please be careful, this script is for the server-side installation and only supports one connection at the same time.

**Comment by hkbbdx** [comment]
Okay thank you
