### ISSUE TITLE
Warzone

### ISSUE THREAD

**Issue by MarlPH** [xiahualiu/wg_gaming_installer#2]
hello, any chance you could make this work with warzone? browsing etc. it works, but when tried for warzone it just keeps on searching for a match, kinda stucks in there.

**Comment by xiahualiu** [comment]
I played Call of Duty series before, Activision uses a ping based match system. **If you have a >100ms lag between your server and the local pc, then it is unlikely you will find a match**. Like I said, find a server close to your location is important, especially for FPS games. For my case I am using a VPS in New York which is only 1-2 hundred miles away from my location. Maybe you can try https://gameserverping.com/cod-modern-warfare to see if the ping is right when using Wireguard.

If you are getting NAT Moderate in game which forbids your match, it is probably a firewall problem on Windows.

1. Close your game, follow steps at https://us.battle.net/support/en/article/7842 to reset your firewall.
2. Then at the next start, there will be a firewall prompt. 
3. **Make sure your check both private and public network options**.

I just did a test and everything went well, I found a match within 90ms range.

![example](https://user-images.githubusercontent.com/49677912/131784343-1144d3e6-0cd9-43bf-b290-ea3d7f0ad5e8.png)

And the match system also takes your skills, statistics into consideration, you can only play with a group of similar level players, if you are too noob or too pro, it is also hard to find a match with others.

**Comment by MarlPH** [comment]
hey, thanks for replying.

after i post here i tested on multiplayer and was able to play. my server region is sgp, ping around 60ms. but still i'm stuck on searching for match on warzone, though i test search only on plunder. 

actually, and i am not comparing, glad i found this installer of yours, some users were using exitlag, i am from asia and we try to play on US and we were able to find match usually around 200ms. so Activision allows high latency, it just takes time to find match, <5mins.

my NAT type also is Open when connected, same as the image you attached. this is the only vpn i have tested that has open nat type. very nice. 

btw, any chance also you can implement multiple users?

**Comment by xiahualiu** [comment]
You can think this Wireguard configuration maps your local IP:ports to the remote server IP:ports directly, and it works on a very low level (kernel level). In order to have more users, the server needs more than one public IPs and distributes one IP to each user, some server providers allow you to add more IPs but some do not. Support for multiple IPs is not implemented in the installer yet but I will probably add it later. For now, you need multiple servers for multiple users.

**Comment by MarlPH** [comment]
okay, thanks.

anyways, seems only working on CoD Modern Warfare (Multiplayer), but not on Warzone. it takes searching for a match forever.

![image](https://user-images.githubusercontent.com/10401489/132038989-e8e79f04-6320-4be6-936a-d03287b92dc5.png)
