### ISSUE TITLE
How to do full cone nat without choosing port ranges as it used to work before

### ISSUE THREAD

**Issue by Lezhek** [xiahualiu/wg_gaming_installer#27]
title

**Comment by xiahualiu** [comment]
The reason for choosing port range option is, for most applications, you just need to forward a small number of ports. Now multiple clients can share the port resource on the server side, as long as they don't have overlapped forward ports.

I suggest you set up the port forward range based on the application or games you are using or playing, you can google "xxx port forward" to know which ports need to be filled here, for example a Minecraft server uses `25565` as default listening port.

However, you can still get the old behaviors, by providing the following port range:

```
53,80,88,500,1024-32767
```

This will cover most ports used by any games. Make sure you don't have anything listening on these ports like SSH. If you are torrenting, you can find the listening port on the seeding software settings page.

**Comment by Lezhek** [comment]
That's exactly what I needed thank you.
