### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by pukpuker** [xiahualiu/wg_gaming_installer#28]
Hello. Before installing the script, I ran “add-fullcone-nat.sh”, then installed the script itself, entered the necessary ports, but for some reason Nat type is still Moderate.

"NatTypeTester" say: "UdpBlocked"

upd: I tried it on another server, everything worked (surprisingly), but at the same time, the program produces Symmetric

**Comment by xiahualiu** [comment]
Sounds good.

You shouldn't run that shell script manually, the script in the template folder is for the installer script to create the script in `etc/wireguard` during installation, which will then be run automatically by the wireguard service. You can modify it before running the `install.sh` to add your own rules in the input chain.

I am not sure how NatTypeTester works, but I think it detects 3478/udp from the outside, if your forward ports does not cover 3478, the result will be either symmetric or restricted.

**Comment by pukpuker** [comment]
yes, I know, I added all the necessary ports and it still doesn't work. Also, I decided to check 25565 (minecraft server) and it still doesn’t work.

**Comment by xiahualiu** [comment]
The `add-fullcone-nat.sh` is just for advanced user to further customize `nftables` firewall rules if needed (in most cases, users don't need to know anything about it). 

During the installation there is a question for the forward port range after you create a client. You can input like: `80,25565,27015-27050`. The script will then **automatically generate pre-routing rules for your forward port range and add it to the script**. Ports/port ranges input here should be separated by comma `,` with no space in between them.

There are also firewall rules on the local PC side, you still need to allow Minecraft to go through Windows firewall if there are any pop-ups.

**Comment by pukpuker** [comment]
80,443,25565,6672,27015,27031-27036,61455-61458
not working... Firewall on PC is disabled

**Comment by xiahualiu** [comment]
Are you running this script on the server with a public IP? I mean the server ip address should not starts with `10.xx.xx.xx` or `192.xx.xx.xx`. 

After your client WG is connected on your PC, can you try visiting youtube.com or google.com in your browser? You should still have internet access on your local PC after it is connected..

**Comment by pukpuker** [comment]
Of course, you will forgive me, but I’m not that stupid) of course with a public IP, also when connecting, all sites open, including 2ip.io (and it shows the server IP)

**Comment by pukpuker** [comment]
> Try this in your pc's Windows PowerShell:
> 
> ```postscript
> python3 -m http.server 80
> ```
> 
> And use your phone or something else to access `<pub-ip-addr>:80` see if the HTTP website works. If it doesn't work there may be some issues.

yes, it works.

**Comment by xiahualiu** [comment]
So the VPN works, your problem may be due to your game server configuration problems.

Like you incorrectly set the server IP address to `127.0.0.1` `[::1]`, which should be `0.0.0.0` `[::]` instead.

**Comment by pukpuker** [comment]
![image](https://github.com/user-attachments/assets/6de04150-91cd-49aa-a465-428f922e96ae)
so...  net.ipv4.ip_local_reserved_ports = 65391,80,443,6672,61455,61456,61457,61458
All ports has been unlocked, but NAT pmp / pcp disabled, upnp disabled too

**Comment by xiahualiu** [comment]
Are you playing RD Online?

I found this :

https://portforward.com/red-dead-online/

If you are playing on Steam, you need to forward **both** TCP and UDP ranges listed on the table.

So the forward ports should be:

```
4380,6672,27000-27037,30211-30217,61455-61458
```

**Comment by pukpuker** [comment]
> Вы играете в RD Online?
> 
> Я нашел это:
> 
> https://portforward.com/red-dead-online/
> 
> Если вы играете в Steam, вам необходимо переслать **оба** диапазона TCP и UDP, указанные в таблице.
> 
> Таким образом, порты переадресации должны быть следующими:
> 
> ```
> 4380,6672,27000-27037,30211-30217,61455-61458
> ```
It's GTA Online, but I set ports: * wg0client [23-65100,65105-65535]

**Comment by xiahualiu** [comment]
That is probably too much. You can google how many ports does GTA Online use.

For example:

https://portforward.com/help/grand-theft-auto-online/

**Comment by pukpuker** [comment]
> That is probably too much. You can google how many ports does GTA Online use.
> 
> For example:
> 
> https://portforward.com/help/grand-theft-auto-online/

I tried to open specific ports that are listed on both this site and another site, but nothing worked. Therefore, in the end I specified almost all available ports and everything worked. I asked them to create a new config file, maybe I'm doing something wrong?

**Comment by xiahualiu** [comment]
Yes, if the reserved ports are too much, they the Linux OS may not have enough ports to use to create new connections. But as long as you don't see any connection problems, it is fine.

**Comment by pukpuker** [comment]
When I tried to specify all ports from 23 to 65535 I couldn't connect, so I freed up 10 ports that Wireguard can use and got 23-65100,65105-65535.
But everything is useless

**Comment by pukpuker** [comment]
so... what can I do?

**Comment by xiahualiu** [comment]
> so... what can I do?

Sorry, what is your question?

**Comment by pukpuker** [comment]
> > so... what can I do?
> 
> Sorry, what is your question?

what can I do if it doesn't work?

**Comment by pukpuker** [comment]
The connection itself works and works. Specifically, NAT does not work

**Comment by EasternGamer** [comment]
After reverting to 60355ea where it uses iptables, port forwarding works again. So like, maybe something to do with the new method used?

**Comment by xiahualiu** [comment]
Which game were you testing? GTA V Online? I can test later today.

The old script blindly port forwards most ports, which is kind of dangerous as it exposes unnecessary ports on your local PC, but it works out of the box for most games. 

The new script forwards ports per peer and is more flexible, also allows more peers at the same time. The only catch is that you need to provide the forward port range list for a certain peer.

For NAT tester, it does not work with the new script, as it detects random ports to determine the overall machine NAT type. For the ports you forwarded, they will have NAT level equals to open but not the rest of the ports.

All the rules are the same. They should have no difference between `iptables` or `nftables`.

**Comment by EasternGamer** [comment]
I used the simple website https://portchecker.co/ to check and an HTTP server. The new script opened none of the ports I asked. The old script opened the desired ports.

I used the range 80,88,6500-27016,27019-65000 for the new script. My HTTP server was on 20000. I couldn't connect to the HTTP server at all on the new script, but the old script I could.

My only other idea is that having multiple users on the same port forward ranges might have had conflicts? Not sure.

**Comment by EasternGamer** [comment]
My last and final idea is that something with my VPS I used had a bad setup. I did a full reset for the old script because they were different, but not sure if I did it for the new script when I set it up.

**Comment by xiahualiu** [comment]
You shouldn't have overlapped ports between different peers. If peer1 has 80 and you add peer2, which also has 80, then 80 on peer1 will work but not peer2.

Also, there are Windows firewall reasons. You need to add inbound rules for your application on Windows.

Typically, the first time an application receives a connection request, there will be a Windows firewall prompt to let you choose either allow it or deny it. You need to allow it.

**Comment by EasternGamer** [comment]
I will give the new script a shot again in like 4 days. I just have some work that requires the port to be working for the next 4 days without problems. Since I have it working right now, don't want to mess with it until then.

However, I thank you for this amazing script. It saves a lot of time. I really liked the multiple-user options. As we have seen, probably best to have a note when setting up, or a check/warning about the ports being overriden by other clients.

**Comment by xiahualiu** [comment]
Thanks for your 👍. 

I will add the port range conflict detection part soon, maybe over the next few weekends. It doesn't really break the whole system now, so I was kind of lazy.
