### ISSUE TITLE
i can use ipv4 and ipv6?

### ISSUE THREAD

**Issue by DEAM0** [xiahualiu/wg_gaming_installer#29]

**Comment by xiahualiu** [comment]
Yes, both IPv4 and IPv6 are supported.

**Comment by DEAM0** [comment]
Could I use two at once?

**Comment by xiahualiu** [comment]
You need to give server network information for both IPv4 and IPv6 at the first time. You need to input the public IPv6 if you want to use it on IPv6. If your server is IPv6 only you can only give the IPv6 address.

IPv6 and IPv4 connection are separated, if you give only IPv4 and not IPv6, you will not have IPv6 working for WG.

**Comment by DEAM0** [comment]
and how to work to ipv6 and ipv4? Just seperate with ,?

**Comment by xiahualiu** [comment]
It is pretty straight forward during the installation. There is one question for IPv4 and one question for IPv6.

**Comment by DEAM0** [comment]
Can I assign multiple ip addresses to your script? I have vps and I want to buy another ip address, is it then possible to route traffic through the same ip address if the first one is already running?

**Comment by xiahualiu** [comment]
yes, you can. You can give the IPv4 you want the peer to use (the ipv4 peer uses to connect the server), and it can generate peer conf based on that ipv4 address.

The ipv4 address and ipv6 address you tell the script is just for generating peer configurations. You can also modify the peer conf EndPointIP with the other IPv4 address manually afterward.

**Comment by DEAM0** [comment]
Thanks
