### ISSUE TITLE
Is there support multiple ip for load balancer on public ip?

### ISSUE THREAD

**Issue by DEAM0** [xiahualiu/wg_gaming_installer#33]
Does this script support load balancer? If I were to run multiple IP addresses on one port, I have multiple servers at home that are connected together, so could it work?

**Comment by xiahualiu** [comment]
I think it is possible; the script currently only supports one server IP. You can probably install this on multiple servers and adjust the subnet IPs, so they look like:

10.66.66.1 - server no.1
10.66.66.2 - server no.2
...
10.66.66.100 - client no.1
10.66.66.101 - client no.2

For the server no.1, the WG configuration should be interface 10.66.66.1, and the rest are client peers. You need to make sure this client peer part is same on all servers.

For the client WG configuration the peer should be all these WG servers.

The only problem I can think of is, the AllowedIPs on the client side, if you have multiple server peers on the client side, how do you route the outgoing packet, like route to which server? The incoming packets should be fine, but the outgoing ones will be problematic, and you need to work on that carefully.

**Comment by xiahualiu** [comment]
If your client side is something like a website server, a game server, as long as it doesn't make any outgoing connections, then the above setup should work just fine. Otherwise, you should make sure that, the allowedIPs configuration on the client's side, should be divided into multiple IP ranges. So that the client WG can route packet to the correct WG server.

**Comment by xiahualiu** [comment]
Sorry after thinking for a while I think it is impossible with WireGuard, because WireGuard doesn't track connections on the client side, so your setup cannot be achieved with WireGuard VPN, at least for now.
