### ISSUE TITLE
OpenVZ Support

### ISSUE THREAD

**Issue by BlurryCode** [xiahualiu/wg_gaming_installer#4]
I'm trying to run this script on a OpenVZ server, and reports back it is not supported. There is another script I use to install wireguard on my OpenVPS server and works fine. Could I just apply the postUp and PostDown IPtable commands and likely end up with the same result? Could OpenVZ support be added in the future? I use this script: https://github.com/Nyr/wireguard-install

**Comment by xiahualiu** [comment]
Yes, you can use other install script and add the iptable rules by yourself. This script does not support OpenVZ because it updates the kernel first, which isn't allowed on OpenVZ instances.
