### ISSUE TITLE
how do i make another peer?

### ISSUE THREAD

**Issue by EXT9ND** [xiahualiu/wg_gaming_installer#7]
i would like to use this script on 2 pcs and cant seem to do that
1 peer forwards the ports 
and the 2nd one dosent

**Comment by EXT9ND** [comment]
but currently the script accepts only 1 client on the server side i want it to have 2 client configs is that possible?
thanks for answering btw :)

**Comment by xiahualiu** [comment]
No, but you can use the same client credential on multiple device.

**Comment by xiahualiu** [comment]
Now the script supports multi peers, however you need to tell the port range to forward when creating a peer.
